### ISSUE TITLE
Add value to kwargs for get_element()

### ISSUE THREAD

**Issue by GeneralStrike** [red-and-black/elemental#4]
[get_element](https://elemental.readthedocs.io/en/latest/getters.html#get-element) needs "value" added as a possible kwarg.

Use case: Django form templates don't add ids or names to options in a select or multi select, but does add a "value" attribute. The only way to get an option at the moment is via "text" or "partial text", but there are cases where this is not easy.

 - [x] Add value to kwargs for get_element
 - [x] Add value to kwargs for get_elements
 - [x] Add tests for get_element(value="value")
 - [x] Add tests for get_elements(value="value")
 - [x] Add kwarg to list in get_element docs
 - [x] Add kwarg to list in get_elements docs
 - [x] Add examples to documentation for get_element
 - [x] Add examples to documentation for get_elements

**Comment by gamesbook** [comment]
First issue encountered when starting with elemental :- _"I want to select this item from the drop-down list based on its value... oh, I can't"_

**Comment by GeneralStrike** [comment]
@gamesbook this is in the latest release :)

**Comment by gamesbook** [comment]
When I try and install the latest version:
```
$ pip install python-elemental==0.6.2
ERROR: Could not find a version that satisfies the requirement python-elemental==0.6.2 (from versions: 0.1, 0.2, 0.2.1, 0.3)
```
